server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/ms_email
spring.datasource.username=root
spring.datasource.password=2003
spring.jpa.hibernate.ddl-auto=update
spring.application.name=email
spring.rabbitmq.addresses=amqps://muklssiy:R0Fb1kGSYn-r537CD4LKgfwtM-Q5xXZA@beaver.rmq.cloudamqp.com/muklssiy
broker.queue.email.name=default.email
